name: Full Stack CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build React app
        run: |
          cd frontend
          npm run build

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run backend
        run: |
          echo "Backend build successful"